import { useDisclosure, UseDisclosureProps } from "@chakra-ui/react"
import { createContext, ReactNode, useContext, useEffect, useState } from "react"
import { IconType } from "react-icons"
import { AiOutlineEye } from "react-icons/ai"
import { BsNewspaper, BsWallet2 } from "react-icons/bs"
import { FiSettings } from "react-icons/fi"
import { UseResponsiveStatus, useResponsiveStatus } from "../hooks/useResponsiveStatus"